name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python src/test_runner.py
    
    - name: Create distribution archive
      run: |
        # Create release directory
        mkdir release
        
        # Copy source files
        xcopy src release\src\ /E /I
        xcopy logs release\logs\ /E /I
        
        # Copy installation and launch scripts
        copy install.ps1 release\
        copy install.bat release\
        copy launch.ps1 release\
        copy run.bat release\
        copy validate_phase2.ps1 release\
        
        # Copy documentation
        copy README.md release\
        copy LICENSE release\
        copy requirements.txt release\
        copy COMPLETED.md release\
        
        # Create archive
        powershell Compress-Archive -Path release\* -DestinationPath backupussy-${{ github.ref_name }}.zip
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: BackupUSSY ${{ github.ref }}
        body: |
          ## BackupUSSY Release ${{ github.ref_name }}
          
          ### Features
          - Complete LTO tape archiving solution
          - Modern GUI with PySimpleGUI
          - SQLite database with search capabilities
          - Stream and cached archive modes
          - Dual tape support for redundancy
          - Comprehensive logging and monitoring
          - Automated installation scripts
          
          ### Installation
          1. Download `backupussy-${{ github.ref_name }}.zip`
          2. Extract to desired location
          3. Run `install.ps1` as Administrator (or `install.bat` for basic setup)
          4. Launch with `run.bat`
          
          ### System Requirements
          - Windows 10/11
          - Python 3.7+
          - LTO tape drive
          
          See README.md for complete installation and usage instructions.
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./backupussy-${{ github.ref_name }}.zip
        asset_name: backupussy-${{ github.ref_name }}.zip
        asset_content_type: application/zip

